<?php
/**
 * BtiDataSchemaTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ЦИАН АПИ
 *
 * <a href=\"https://www.cian.ru/help/about/37970/\">Условия использования</a>  ## Описание  ### Авторизация Для работы с API необходимо получить ключ авторизации. Для получения ключа нужно написать письмо на import@cian.ru с темой \"ACCESS KEY\" и названием агентства, которое вы представляете. Менеджер уточнит подробности и пришлет ACCESS KEY. Для каждой учетной записи на ЦИАН выдается отдельный ключ авторизации.  Далее все запросы выполняются с заголовком: `Authorization: Bearer <ACCESS KEY>`.  ### Дата и время Формат данных для времени (date-time): `2020-07-18 04:52:33.051204` и для даты (date): `2020-07-18`   Во всех запросах дата и время передаются и возвращаются в таймзоне `Europe/Moscow`.
 *
 * OpenAPI spec version: 1.0
 * Contact: import@cian.ru
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.18
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * BtiDataSchemaTest Class Doc Comment
 *
 * @category    Class
 * @description BtiDataSchema
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BtiDataSchemaTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BtiDataSchema"
     */
    public function testBtiDataSchema()
    {
    }

    /**
     * Test attribute "ceiling_height"
     */
    public function testPropertyCeilingHeight()
    {
    }

    /**
     * Test attribute "chute_count"
     */
    public function testPropertyChuteCount()
    {
    }

    /**
     * Test attribute "entrances"
     */
    public function testPropertyEntrances()
    {
    }

    /**
     * Test attribute "flat_count"
     */
    public function testPropertyFlatCount()
    {
    }

    /**
     * Test attribute "floor_max"
     */
    public function testPropertyFloorMax()
    {
    }

    /**
     * Test attribute "has_playground"
     */
    public function testPropertyHasPlayground()
    {
    }

    /**
     * Test attribute "has_sportsground"
     */
    public function testPropertyHasSportsground()
    {
    }

    /**
     * Test attribute "house_gas_supply_type"
     */
    public function testPropertyHouseGasSupplyType()
    {
    }

    /**
     * Test attribute "house_heat_supply_type"
     */
    public function testPropertyHouseHeatSupplyType()
    {
    }

    /**
     * Test attribute "house_material_type"
     */
    public function testPropertyHouseMaterialType()
    {
    }

    /**
     * Test attribute "house_overhaul_fund_type"
     */
    public function testPropertyHouseOverhaulFundType()
    {
    }

    /**
     * Test attribute "house_overlap_type"
     */
    public function testPropertyHouseOverlapType()
    {
    }

    /**
     * Test attribute "is_emergency"
     */
    public function testPropertyIsEmergency()
    {
    }

    /**
     * Test attribute "lifts"
     */
    public function testPropertyLifts()
    {
    }

    /**
     * Test attribute "year_release"
     */
    public function testPropertyYearRelease()
    {
    }
}
